# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CabMapTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CabMapTest
    pod 'GoogleMaps', '4.2.0'
    pod 'GooglePlaces', '4.2.0'
  
  target 'CabMapTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CabMapTestUITests' do
    # Pods for testing
  end

end
